# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "strata-noble"

# Production project reference
# Project URL: https://bvneqoevtwodyfqglpzi.supabase.co
# Project Reference: bvneqoevtwodyfqglpzi
# Region: us-west-1

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "realtime", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "https://stratanoble.com"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
enable_confirmations = false