#
# ANX Command Center - Desktop Shortcut Installer
# Creates desktop shortcut for one-click Command Center access
#

param(
    [string]$TargetUser = $env:USERNAME
)

# Configuration
$ANXRoot = "C:\Dev\.claude-anx"
$LauncherScript = "$ANXRoot\scripts\start_command_center.ps1"
$DesktopPath = [Environment]::GetFolderPath("Desktop")
$ShortcutPath = "$DesktopPath\ANX Command Center.lnk"

# Logging function
function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message"
}

function Test-Prerequisites {
    Write-Log "Checking prerequisites..."

    # Check if launcher script exists
    if (-not (Test-Path $LauncherScript)) {
        Write-Log "Launcher script not found: $LauncherScript" "ERROR"
        return $false
    }

    # Check if PowerShell execution policy allows scripts
    $executionPolicy = Get-ExecutionPolicy -Scope CurrentUser
    if ($executionPolicy -eq "Restricted") {
        Write-Log "PowerShell execution policy is Restricted. Consider running: Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned" "WARN"
    }

    Write-Log "Prerequisites check passed" "SUCCESS"
    return $true
}

function Create-Shortcut {
    Write-Log "Creating desktop shortcut..."

    try {
        # Create WScript Shell COM object
        $WScriptShell = New-Object -ComObject WScript.Shell

        # Create shortcut object
        $Shortcut = $WScriptShell.CreateShortcut($ShortcutPath)

        # Configure shortcut properties
        $Shortcut.TargetPath = "powershell.exe"
        $Shortcut.Arguments = "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$LauncherScript`" -Silent"
        $Shortcut.WorkingDirectory = $ANXRoot
        $Shortcut.Description = "Launch ANX Command Center with one click"
        $Shortcut.IconLocation = "shell32.dll,21"  # Command prompt icon

        # Save shortcut
        $Shortcut.Save()

        Write-Log "Desktop shortcut created: $ShortcutPath" "SUCCESS"
        return $true
    }
    catch {
        Write-Log "Failed to create shortcut: $($_.Exception.Message)" "ERROR"
        return $false
    }
}

function Test-Shortcut {
    Write-Log "Testing shortcut creation..."

    if (Test-Path $ShortcutPath) {
        Write-Log "Shortcut file exists: $ShortcutPath" "SUCCESS"

        # Get shortcut properties to verify
        $WScriptShell = New-Object -ComObject WScript.Shell
        $Shortcut = $WScriptShell.CreateShortcut($ShortcutPath)

        Write-Log "Target: $($Shortcut.TargetPath)" "INFO"
        Write-Log "Arguments: $($Shortcut.Arguments)" "INFO"
        Write-Log "Working Directory: $($Shortcut.WorkingDirectory)" "INFO"

        return $true
    } else {
        Write-Log "Shortcut file not found after creation" "ERROR"
        return $false
    }
}

function Write-InstallationReceipt {
    param([bool]$Success, [string]$ErrorMessage = "")

    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ"
    $receiptPath = "$ANXRoot\receipts\DESKTOP_SHORTCUT_INSTALL_RECEIPT.md"

    # Ensure receipts directory exists
    $receiptsDir = Split-Path $receiptPath -Parent
    if (-not (Test-Path $receiptsDir)) {
        New-Item -ItemType Directory -Path $receiptsDir -Force | Out-Null
    }

    $status = if ($Success) { "SUCCESS" } else { "FAILED" }
    $content = @"
# Desktop Shortcut Installation Receipt

**Date:** $timestamp
**Status:** $status
**Target User:** $TargetUser

## Installation Details

### Shortcut Configuration
- **Name:** ANX Command Center
- **Location:** $ShortcutPath
- **Target:** PowerShell.exe
- **Arguments:** -ExecutionPolicy Bypass -WindowStyle Hidden -File "$LauncherScript" -Silent
- **Working Directory:** $ANXRoot
- **Icon:** Command prompt (shell32.dll,21)

### Launcher Script
- **Path:** $LauncherScript
- **Exists:** $(Test-Path $LauncherScript)

### Installation Process
- **Prerequisites Check:** $(if ($Success) { "PASSED" } else { "FAILED" })
- **Shortcut Creation:** $(if ($Success) { "SUCCESS" } else { "FAILED" })
- **Verification:** $(if ($Success) { "PASSED" } else { "FAILED" })

$(if ($ErrorMessage) {
"## Error Details
$ErrorMessage"
} else {
"## Usage Instructions
1. **Double-click** the 'ANX Command Center' shortcut on your desktop
2. **Wait** for the Command Center to start automatically (< 30 seconds)
3. **Browser** will open automatically to the Command Center UI
4. **No manual steps** required - complete automation

## Shortcut Behavior
- **Window Style:** Hidden (no PowerShell window visible)
- **Execution Policy:** Bypassed for this script only
- **Error Handling:** Creates receipt in $ANXRoot\receipts\ on each run
- **Silent Mode:** Minimal console output during startup"
})

---
Generated by: Desktop Shortcut Installer
"@

    try {
        Set-Content -Path $receiptPath -Value $content -Encoding UTF8
        Write-Log "Installation receipt written: $receiptPath" "SUCCESS"
    }
    catch {
        Write-Log "Failed to write installation receipt: $($_.Exception.Message)" "WARN"
    }
}

# Main execution
function Main {
    Write-Log "ANX Command Center - Desktop Shortcut Installer" "INFO"
    Write-Log "================================================" "INFO"

    try {
        # Step 1: Check prerequisites
        if (-not (Test-Prerequisites)) {
            Write-InstallationReceipt -Success $false -ErrorMessage "Prerequisites check failed"
            exit 1
        }

        # Step 2: Create shortcut
        if (-not (Create-Shortcut)) {
            Write-InstallationReceipt -Success $false -ErrorMessage "Shortcut creation failed"
            exit 1
        }

        # Step 3: Verify shortcut
        if (-not (Test-Shortcut)) {
            Write-InstallationReceipt -Success $false -ErrorMessage "Shortcut verification failed"
            exit 1
        }

        # Step 4: Write success receipt
        Write-InstallationReceipt -Success $true

        Write-Log "================================================" "INFO"
        Write-Log "Desktop shortcut installed successfully!" "SUCCESS"
        Write-Log "Shortcut location: $ShortcutPath" "SUCCESS"
        Write-Log "================================================" "INFO"

        Write-Host ""
        Write-Host "Desktop shortcut created!" -ForegroundColor Green
        Write-Host "Location: $ShortcutPath" -ForegroundColor Cyan
        Write-Host "Double-click to launch ANX Command Center" -ForegroundColor Cyan
        Write-Host ""

        exit 0
    }
    catch {
        Write-Log "Unexpected error: $($_.Exception.Message)" "ERROR"
        Write-InstallationReceipt -Success $false -ErrorMessage "Unexpected error: $($_.Exception.Message)"
        exit 1
    }
}

# Execute main function
Main