/**
 * Ops Controls API Routes
 * Handles kill switch, budget caps, and exceptions
 */

const express = require('express');
const router = express.Router();
const dbService = require('../services/database');
const fs = require('fs').promises;
const path = require('path');

const ANX_ROOT = 'C:\\Dev\\.claude-anx';
const OPS_CONFIG_PATH = path.join(ANX_ROOT, 'state', 'ops_config.json');

// Load or create ops configuration
async function loadOpsConfig() {
  try {
    const content = await fs.readFile(OPS_CONFIG_PATH, 'utf-8');
    return JSON.parse(content);
  } catch {
    // Default configuration
    const defaultConfig = {
      kill_switch: false,
      budget_caps: {
        daily_operations: 1000,
        max_job_retries: 3,
        max_concurrent_jobs: 10
      },
      exceptions_enabled: true,
      auto_recovery: true
    };
    await saveOpsConfig(defaultConfig);
    return defaultConfig;
  }
}

async function saveOpsConfig(config) {
  await fs.writeFile(OPS_CONFIG_PATH, JSON.stringify(config, null, 2));
}

// GET /api/ops/status - Get overall ops status
router.get('/status', async (req, res) => {
  try {
    const config = await loadOpsConfig();

    // Get current queue stats
    const queueStats = await dbService.get(`
      SELECT
        COUNT(*) as total,
        SUM(CASE WHEN status = 'PENDING' THEN 1 ELSE 0 END) as pending,
        SUM(CASE WHEN status = 'EXECUTING' THEN 1 ELSE 0 END) as executing,
        SUM(CASE WHEN status IN ('COMPLETED', 'SUCCESS') THEN 1 ELSE 0 END) as completed,
        SUM(CASE WHEN status IN ('FAILED', 'TIMEOUT', 'CRASH') THEN 1 ELSE 0 END) as failed
      FROM queue
      WHERE created_at >= datetime('now', '-24 hours')
    `);

    // Get recent exceptions
    const recentExceptions = await dbService.all(`
      SELECT id, last_error, created_at
      FROM queue
      WHERE status IN ('FAILED', 'TIMEOUT', 'CRASH')
      AND created_at >= datetime('now', '-1 hour')
      ORDER BY created_at DESC
      LIMIT 10
    `);

    res.json({
      config,
      queue_stats: queueStats,
      recent_exceptions: recentExceptions,
      system_status: config.kill_switch ? 'STOPPED' : 'RUNNING'
    });
  } catch (error) {
    console.error('Error fetching ops status:', error);
    res.status(500).json({ error: 'Failed to fetch ops status' });
  }
});

// GET /api/ops/kill-switch - Get kill switch status
router.get('/kill-switch', async (req, res) => {
  try {
    const config = await loadOpsConfig();
    res.json({
      enabled: config.kill_switch,
      message: config.kill_switch
        ? 'System execution is STOPPED'
        : 'System execution is RUNNING'
    });
  } catch (error) {
    console.error('Error fetching kill switch:', error);
    res.status(500).json({ error: 'Failed to fetch kill switch status' });
  }
});

// POST /api/ops/kill-switch - Toggle kill switch
router.post('/kill-switch', async (req, res) => {
  try {
    const { enabled } = req.body;
    const config = await loadOpsConfig();

    config.kill_switch = !!enabled;
    await saveOpsConfig(config);

    if (enabled) {
      // Stop all pending jobs
      await dbService.run(`
        UPDATE queue
        SET status = 'STOPPED', last_error = 'Kill switch activated'
        WHERE status = 'PENDING'
      `);

      // Create system receipt
      const receiptContent = `# SYSTEM KILL SWITCH ACTIVATED

**Date:** ${new Date().toISOString()}
**Action:** Kill switch ENABLED
**Impact:** All pending jobs stopped
**Operator:** Command Center

## System State
- Previous Status: RUNNING
- Current Status: STOPPED
- Jobs Affected: See queue for STOPPED status

## Recovery Instructions
1. Disable kill switch via Command Center
2. Review stopped jobs
3. Rerun necessary operations

---
Generated by: Command Center Ops Control`;

      const receiptPath = path.join(ANX_ROOT, 'receipts', `SYSTEM_KILL_SWITCH_${Date.now()}.md`);
      await fs.writeFile(receiptPath, receiptContent);
    }

    res.json({
      kill_switch: config.kill_switch,
      message: config.kill_switch
        ? 'Kill switch ENABLED - all operations stopped'
        : 'Kill switch DISABLED - operations resumed'
    });
  } catch (error) {
    console.error('Error toggling kill switch:', error);
    res.status(500).json({ error: 'Failed to toggle kill switch' });
  }
});

// GET /api/ops/budget-caps - Get budget cap settings
router.get('/budget-caps', async (req, res) => {
  try {
    const config = await loadOpsConfig();

    // Get today's usage
    const todayUsage = await dbService.get(`
      SELECT COUNT(*) as operations_today
      FROM queue
      WHERE created_at >= datetime('now', 'start of day')
    `);

    res.json({
      caps: config.budget_caps,
      usage: {
        operations_today: todayUsage.operations_today,
        remaining: config.budget_caps.daily_operations - todayUsage.operations_today
      }
    });
  } catch (error) {
    console.error('Error fetching budget caps:', error);
    res.status(500).json({ error: 'Failed to fetch budget caps' });
  }
});

// PUT /api/ops/budget-caps - Update budget caps
router.put('/budget-caps', async (req, res) => {
  try {
    const { daily_operations, max_job_retries, max_concurrent_jobs } = req.body;
    const config = await loadOpsConfig();

    if (daily_operations !== undefined) {
      config.budget_caps.daily_operations = parseInt(daily_operations);
    }
    if (max_job_retries !== undefined) {
      config.budget_caps.max_job_retries = parseInt(max_job_retries);
    }
    if (max_concurrent_jobs !== undefined) {
      config.budget_caps.max_concurrent_jobs = parseInt(max_concurrent_jobs);
    }

    await saveOpsConfig(config);

    res.json({
      budget_caps: config.budget_caps,
      message: 'Budget caps updated'
    });
  } catch (error) {
    console.error('Error updating budget caps:', error);
    res.status(500).json({ error: 'Failed to update budget caps' });
  }
});

// GET /api/ops/exceptions - Get recent exceptions
router.get('/exceptions', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 50;

    const exceptions = await dbService.all(`
      SELECT
        id,
        json_extract(payload, '$.job_name') as job_name,
        json_extract(payload, '$.repo_id') as repo_id,
        status,
        last_error,
        created_at,
        attempts
      FROM queue
      WHERE status IN ('FAILED', 'TIMEOUT', 'CRASH')
      ORDER BY created_at DESC
      LIMIT ?
    `, [limit]);

    // Group by error type
    const errorGroups = {};
    exceptions.forEach(ex => {
      const errorKey = ex.last_error ? ex.last_error.substring(0, 50) : 'Unknown error';
      if (!errorGroups[errorKey]) {
        errorGroups[errorKey] = [];
      }
      errorGroups[errorKey].push(ex);
    });

    res.json({
      exceptions,
      grouped: errorGroups,
      total: exceptions.length
    });
  } catch (error) {
    console.error('Error fetching exceptions:', error);
    res.status(500).json({ error: 'Failed to fetch exceptions' });
  }
});

module.exports = router;