-- =============================================================================
-- CFO Agent Finance Schema Migration
-- =============================================================================
-- Entity: STRATANOBLE
-- Version: 1.0.0
--
-- This migration creates the complete finance schema for the CFO Agent.
-- READ-ONLY: The CFO Agent writes to these tables only, never to external systems.
-- =============================================================================

-- Create finance schema
create schema if not exists finance;

-- =============================================================================
-- SEGMENTS TABLE
-- =============================================================================
-- Configures each business segment (Direct Cuts, REIL/Q, future ventures)

create table if not exists finance.segments (
  segment_id text primary key,
  type text not null check (type in ('marketplace', 'saas', 'services')),
  merchant_of_record boolean not null default false,
  finance_policy_version text not null default 'v1',
  currency text not null default 'USD',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table finance.segments is 'Business segment configuration for multi-venture support';
comment on column finance.segments.merchant_of_record is 'If true, payouts are treated as COGS instead of pass-through liability';

-- =============================================================================
-- METRIC DEFINITIONS TABLE
-- =============================================================================
-- Canonical definitions of all metrics computed by the CFO Agent

create table if not exists finance.metric_definitions (
  metric_key text primary key,
  display_name text not null,
  description text not null,
  unit text not null,
  formula text not null,
  segment_types text[] not null default '{}',
  policy_dependencies text[] not null default '{}',
  version text not null default 'v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table finance.metric_definitions is 'Canonical metric definitions enforced by CFO Agent';

-- =============================================================================
-- METRIC SNAPSHOTS TABLE
-- =============================================================================
-- Immutable snapshots of metrics at specific points in time

create table if not exists finance.metric_snapshots (
  id uuid primary key default gen_random_uuid(),
  entity_id text not null default 'STRATANOBLE',
  segment_id text not null references finance.segments(segment_id),
  period text not null,
  period_type text not null check (period_type in ('daily', 'weekly', 'monthly', 'quarterly')),
  metrics jsonb not null default '{}',
  policy_version text not null,
  ruleset_version text not null,
  data_quality jsonb not null default '{}',
  is_closed boolean not null default false,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  created_at timestamptz not null default now(),
  created_by text not null default 'cfo_agent'
);

create index idx_metric_snapshots_segment_period on finance.metric_snapshots(segment_id, period);
create index idx_metric_snapshots_entity_period on finance.metric_snapshots(entity_id, period);

comment on table finance.metric_snapshots is 'Immutable metric snapshots with policy and data quality tracking';
comment on column finance.metric_snapshots.is_closed is 'True when books are closed for this period - final numbers';

-- =============================================================================
-- ALERT EVENTS TABLE
-- =============================================================================
-- Alerts generated by the CFO Agent based on ruleset thresholds

create table if not exists finance.alert_events (
  id uuid primary key default gen_random_uuid(),
  entity_id text not null default 'STRATANOBLE',
  segment_id text references finance.segments(segment_id),
  alert_key text not null,
  category text not null check (category in ('cash_runway', 'marketplace_health', 'saas_health', 'stripe_operational', 'data_quality')),
  severity text not null check (severity in ('critical', 'high', 'warning', 'info')),
  title text not null,
  description text not null,
  evidence jsonb not null default '{}',
  threshold_triggered text not null,
  current_value numeric not null,
  threshold_value numeric not null,
  ruleset_version text not null,
  policy_version text not null,
  acknowledged_at timestamptz,
  acknowledged_by text,
  resolved_at timestamptz,
  drilldown_request_id uuid,
  created_at timestamptz not null default now()
);

create index idx_alert_events_entity_created on finance.alert_events(entity_id, created_at desc);
create index idx_alert_events_severity on finance.alert_events(severity) where resolved_at is null;

comment on table finance.alert_events is 'Alerts generated by CFO Agent ruleset evaluation';

-- =============================================================================
-- SCENARIO RUNS TABLE
-- =============================================================================
-- Scenario planning runs with inputs and outputs

create table if not exists finance.scenario_runs (
  id uuid primary key default gen_random_uuid(),
  entity_id text not null default 'STRATANOBLE',
  segment_id text references finance.segments(segment_id),
  scenario_type text not null check (scenario_type in ('pricing_change', 'marketing_spend', 'hiring', 'feature_launch')),
  name text not null,
  description text,
  inputs jsonb not null,
  outputs jsonb not null,
  assumptions jsonb not null default '{}',
  baseline_snapshot_id uuid references finance.metric_snapshots(id),
  policy_version text not null,
  created_at timestamptz not null default now(),
  created_by text not null default 'cfo_agent'
);

create index idx_scenario_runs_entity on finance.scenario_runs(entity_id, created_at desc);

comment on table finance.scenario_runs is 'Scenario planning runs with full audit trail';

-- =============================================================================
-- DRILLDOWN REQUESTS TABLE
-- =============================================================================
-- Requests from CFO Agent to Accountant Agent for investigation

create table if not exists finance.drilldown_requests (
  id uuid primary key default gen_random_uuid(),
  entity_id text not null default 'STRATANOBLE',
  alert_event_id uuid references finance.alert_events(id),
  reason text not null,
  period text not null,
  accounts text[] not null default '{}',
  need text not null,
  status text not null check (status in ('pending', 'in_progress', 'completed', 'failed')) default 'pending',
  response jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index idx_drilldown_requests_status on finance.drilldown_requests(status) where status != 'completed';

comment on table finance.drilldown_requests is 'CFO Agent requests to Accountant Agent for investigation';

-- =============================================================================
-- AGENT SCHEDULES TABLE
-- =============================================================================
-- Required update windows for scheduled jobs

create table if not exists finance.agent_schedules (
  id uuid primary key default gen_random_uuid(),
  job_key text not null unique,
  cadence text not null check (cadence in ('hourly', 'daily', 'weekly', 'monthly', 'quarterly', 'on_demand')),
  run_at_time text,
  timezone text not null default 'America/Los_Angeles',
  enabled boolean not null default true,
  last_run_at timestamptz,
  next_run_at timestamptz,
  last_run_status text check (last_run_status in ('success', 'failure', 'running')),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table finance.agent_schedules is 'Required update windows enforced by CFO Agent';
comment on column finance.agent_schedules.run_at_time is 'Time in HH:MM format for scheduled runs';

-- =============================================================================
-- RULESETS TABLE
-- =============================================================================
-- Configurable threshold rules for alerts

create table if not exists finance.rulesets (
  ruleset_key text primary key,
  description text not null,
  rules jsonb not null,
  version text not null default 'v1',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table finance.rulesets is 'Configurable alert thresholds and detection rules';

-- =============================================================================
-- CFO BRIEFINGS TABLE
-- =============================================================================
-- Plain-language CFO briefings with recommendations

create table if not exists finance.cfo_briefings (
  id uuid primary key default gen_random_uuid(),
  entity_id text not null default 'STRATANOBLE',
  period text not null,
  briefing jsonb not null,
  policy_version text not null,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  created_at timestamptz not null default now()
);

create index idx_cfo_briefings_period on finance.cfo_briefings(entity_id, period);

comment on table finance.cfo_briefings is 'Plain-language CFO briefings with evidence and recommendations';

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
-- finance.* tables: read access service role only (agents) and admin dashboard role
-- No public access

alter table finance.segments enable row level security;
alter table finance.metric_definitions enable row level security;
alter table finance.metric_snapshots enable row level security;
alter table finance.alert_events enable row level security;
alter table finance.scenario_runs enable row level security;
alter table finance.drilldown_requests enable row level security;
alter table finance.agent_schedules enable row level security;
alter table finance.rulesets enable row level security;
alter table finance.cfo_briefings enable row level security;

-- Service role policies (full access for agents)
create policy "Service role full access on segments"
  on finance.segments for all
  using (auth.role() = 'service_role');

create policy "Service role full access on metric_definitions"
  on finance.metric_definitions for all
  using (auth.role() = 'service_role');

create policy "Service role full access on metric_snapshots"
  on finance.metric_snapshots for all
  using (auth.role() = 'service_role');

create policy "Service role full access on alert_events"
  on finance.alert_events for all
  using (auth.role() = 'service_role');

create policy "Service role full access on scenario_runs"
  on finance.scenario_runs for all
  using (auth.role() = 'service_role');

create policy "Service role full access on drilldown_requests"
  on finance.drilldown_requests for all
  using (auth.role() = 'service_role');

create policy "Service role full access on agent_schedules"
  on finance.agent_schedules for all
  using (auth.role() = 'service_role');

create policy "Service role full access on rulesets"
  on finance.rulesets for all
  using (auth.role() = 'service_role');

create policy "Service role full access on cfo_briefings"
  on finance.cfo_briefings for all
  using (auth.role() = 'service_role');

-- =============================================================================
-- TRIGGERS FOR UPDATED_AT
-- =============================================================================

create or replace function finance.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_segments_updated_at
  before update on finance.segments
  for each row execute function finance.update_updated_at_column();

create trigger update_metric_definitions_updated_at
  before update on finance.metric_definitions
  for each row execute function finance.update_updated_at_column();

create trigger update_agent_schedules_updated_at
  before update on finance.agent_schedules
  for each row execute function finance.update_updated_at_column();

create trigger update_rulesets_updated_at
  before update on finance.rulesets
  for each row execute function finance.update_updated_at_column();
