/**
 * Orchestrator Trigger Handler
 *
 * Core logic for P0 completion orchestration, extracted for reuse by:
 * 1. GitHub Actions workflow (via trigger-next.mjs)
 * 2. Agent Runner API endpoint (via HTTP call)
 *
 * This module handles:
 * - Reading and validating P0 completion signals
 * - Creating GitHub Issues for next validation tasks
 * - Deduplication via marker issues
 */

import fs from "node:fs/promises";
import { execSync } from "node:child_process";
import path from "node:path";

// GitHub API wrapper
async function gh(token, repoPath, apiPath, options = {}) {
  const res = await fetch(`https://api.github.com${apiPath}`, {
    ...options,
    headers: {
      "Authorization": `Bearer ${token}`,
      "Accept": "application/vnd.github+json",
      ...(options.headers || {})
    }
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API error ${res.status}: ${text}`);
  }
  return res.json();
}

// Check if an issue already exists with given title fragment
async function issueExists(token, owner, repo, titleContains) {
  const q = encodeURIComponent(`repo:${owner}/${repo} is:issue "${titleContains}"`);
  const data = await gh(token, null, `/search/issues?q=${q}`);
  return (data.items || []).length > 0;
}

// Create a GitHub Issue
async function createIssue(token, owner, repo, title, body, labels = []) {
  return gh(token, null, `/repos/${owner}/${repo}/issues`, {
    method: "POST",
    body: JSON.stringify({ title, body, labels })
  });
}

// Get current git SHA
function getGitSha(cwd) {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf8", cwd }).trim();
  } catch {
    return "unknown";
  }
}

// Next tasks template
function nextTasksTemplate(signal) {
  return [
    {
      title: `POST-P0: Run test suite + attach proof (${signal.date})`,
      labels: ["sprint:security-hotfix", "agent:qa", "priority:high"],
      body: `## Objective
Run npm test and attach logs as proof artifacts.

## Acceptance Criteria
- [ ] npm test passes
- [ ] Proof saved under \`docs/audits/proofs/${signal.date}/tests.log\`
- [ ] Link proof in SECURITY_GATE_PROOF doc

## Commands
\`\`\`bash
cd apps/website
npm test 2>&1 | node ../../scripts/orchestrator/save-proof.mjs --task VAL-001 --type test-suite
\`\`\`

## Evidence Required
Save test output to: \`docs/audits/proofs/${signal.date}/tests.log\`

---
*Auto-generated by Orchestrator on P0 completion*`
    },
    {
      title: `POST-P0: Run production build + attach proof (${signal.date})`,
      labels: ["sprint:security-hotfix", "agent:platform", "priority:critical"],
      body: `## Objective
Run npm run build for the production target and capture output.

## Acceptance Criteria
- [ ] Production build succeeds
- [ ] Proof saved under \`docs/audits/proofs/${signal.date}/build.log\`
- [ ] Any SSR failures resolved if encountered

## Commands
\`\`\`bash
cd apps/website
npm run build 2>&1 | node ../../scripts/orchestrator/save-proof.mjs --task VAL-002 --type build-output
\`\`\`

## Evidence Required
Save build output to: \`docs/audits/proofs/${signal.date}/build.log\`

## Known Issues to Watch For
- Next.js 15 SSR dynamic API usage in static pages
- Client component hydration mismatches

---
*Auto-generated by Orchestrator on P0 completion*`
    },
    {
      title: `POST-P0: Deploy staging + validate protected routes (${signal.date})`,
      labels: ["sprint:security-hotfix", "agent:platform", "priority:high"],
      body: `## Objective
Deploy to staging and validate JWT-protected routes and middleware behavior.

## Acceptance Criteria
- [ ] /achievery/*, /dashboard/*, /admin/* block unauthenticated access
- [ ] Rate limiting triggers at expected thresholds
- [ ] Proof saved under \`docs/audits/proofs/${signal.date}/staging-validation/\`

## Validation Steps
1. Deploy to staging environment
2. Test protected routes without auth (should redirect to login)
3. Test protected routes with auth (should allow access)
4. Test rate limiting by exceeding threshold
5. Capture screenshots/logs for each test

## Evidence Required
- \`docs/audits/proofs/${signal.date}/staging-validation/unauthenticated-redirect.png\`
- \`docs/audits/proofs/${signal.date}/staging-validation/authenticated-access.png\`
- \`docs/audits/proofs/${signal.date}/staging-validation/rate-limit-trigger.log\`

---
*Auto-generated by Orchestrator on P0 completion*`
    },
    {
      title: `P1: Configure Sentry alerts for error spikes (${signal.date})`,
      labels: ["sprint:security-hotfix", "agent:security", "priority:high"],
      body: `## Objective
Configure alert(s) for error spikes and prove it triggers.

## Acceptance Criteria
- [ ] Alert rule created (document settings)
- [ ] Test event triggers alert delivery
- [ ] Proof saved under \`docs/audits/proofs/${signal.date}/sentry-alert-proof/\`

## Configuration Steps
1. Create Sentry alert rule for error spike (>10 errors in 5 min)
2. Configure notification channel (email/Slack)
3. Trigger test error to verify alert fires
4. Capture screenshot of triggered alert

## Evidence Required
- \`docs/audits/proofs/${signal.date}/sentry-alert-proof/alert-config.png\`
- \`docs/audits/proofs/${signal.date}/sentry-alert-proof/alert-triggered.png\`

---
*Auto-generated by Orchestrator on P0 completion*`
    },
    {
      title: `POST-P0: Update sprint state after validation (${signal.date})`,
      labels: ["sprint:security-hotfix", "agent:pm", "priority:medium"],
      body: `## Objective
Update PM Agent sprint state after all validation tasks complete.

## Acceptance Criteria
- [ ] All POST-P0 tasks marked complete
- [ ] \`docs/sprints/_state.json\` updated with evidence
- [ ] Security gate marked as "passed" with proof links
- [ ] Sprint status report generated

## Commands
\`\`\`bash
npm run agents sprint:status
\`\`\`

## Dependencies
This task should only be marked complete after:
- POST-P0: Run test suite + attach proof
- POST-P0: Run production build + attach proof
- POST-P0: Deploy staging + validate protected routes

---
*Auto-generated by Orchestrator on P0 completion*`
    }
  ];
}

/**
 * Main orchestration handler
 *
 * @param {Object} options
 * @param {string} options.signalPath - Path to signal file
 * @param {string} options.githubToken - GitHub API token
 * @param {string} options.owner - Repository owner
 * @param {string} options.repo - Repository name
 * @param {string} options.runId - GitHub Actions run ID or identifier
 * @param {string} options.cwd - Working directory
 * @returns {Promise<{success: boolean, message: string, tasks_created?: number}>}
 */
export async function triggerOrchestration(options) {
  const { signalPath, githubToken, owner, repo, runId, cwd } = options;

  console.log("Orchestrator Trigger: Checking P0 completion signal...");

  // Read signal file
  let raw;
  try {
    raw = await fs.readFile(signalPath, "utf8");
  } catch (err) {
    console.log(`Signal file not found: ${signalPath}`);
    return { success: true, message: "No signal file found. Nothing to orchestrate." };
  }

  const signal = JSON.parse(raw);

  // Check if signal is complete
  if (signal.status !== "complete") {
    console.log(`Signal not complete. status=${signal.status}`);
    return { success: true, message: `Signal not complete (status=${signal.status}). Nothing to orchestrate.` };
  }

  const sha = getGitSha(cwd);
  console.log(`Signal detected: ${signal.signal} (${signal.date}) sha=${sha} run=${runId}`);

  // Dedupe key with sha + run_id
  const dedupeKey = `Orchestrator: ${signal.signal} ${signal.date} sha=${sha}`;

  // Check for existing trigger with same sha
  if (await issueExists(githubToken, owner, repo, dedupeKey)) {
    console.log("Already triggered for this signal + sha. Exiting.");
    return { success: true, message: "Already triggered for this signal + sha." };
  }

  // Also check for broader date-based dedupe
  const dateDedupeKey = `Orchestrator: ${signal.signal} ${signal.date}`;
  if (await issueExists(githubToken, owner, repo, dateDedupeKey)) {
    console.log("Already triggered for this signal + date. Exiting.");
    return { success: true, message: "Already triggered for this signal + date." };
  }

  console.log("Creating orchestration marker issue...");

  // Format evidence list
  let evidenceList = "";
  if (Array.isArray(signal.evidence)) {
    evidenceList = signal.evidence.map(p => `- \`${p}\``).join('\n');
  } else if (typeof signal.evidence === 'object') {
    evidenceList = Object.entries(signal.evidence).map(([name, p]) => `- ${name}: \`${p}\``).join('\n');
  }

  // Create marker issue
  await createIssue(
    githubToken,
    owner,
    repo,
    dedupeKey,
    `## Automated Orchestration Trigger

Detected completion of \`${signal.signal}\` on ${signal.date}.

### Execution Context
- **SHA:** \`${sha}\`
- **Run ID:** \`${runId}\`
- **Signal Version:** ${signal.version || '1.0'}

### Gates Completed
${Object.entries(signal.gates).map(([gate, status]) => `- ${gate}: ${status}`).join('\n')}

### Evidence Files
${evidenceList}

### Completed Tasks
${(signal.completed_tasks || []).map(t => `- ${t}`).join('\n')}

### Next Steps Created
This trigger has created the following validation tasks:
1. Run test suite + attach proof
2. Run production build + attach proof
3. Deploy staging + validate protected routes
4. Configure Sentry alerts for error spikes
5. Update sprint state after validation

---
*This issue exists to prevent duplicate orchestration runs and serve as an audit trail.*
*Dedupe key: ${dedupeKey}*`,
    ["automation", "orchestrator", "sprint:security-hotfix"]
  );

  console.log("Created marker issue. Creating next tasks...");

  // Create next tasks
  const tasks = nextTasksTemplate(signal);
  for (const t of tasks) {
    await createIssue(githubToken, owner, repo, t.title, t.body, t.labels);
    console.log(`Created issue: ${t.title}`);
  }

  console.log(`\nOrchestrator complete. Created ${tasks.length} tasks.`);

  return {
    success: true,
    message: `Orchestration complete. Created ${tasks.length} validation tasks.`,
    tasks_created: tasks.length,
    dedupe_key: dedupeKey,
  };
}

// Export for use by trigger-next.mjs and API endpoint
export { nextTasksTemplate, issueExists, createIssue, getGitSha };
