name: Security Audit

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: |
        echo "## NPM Security Audit Results" >> $GITHUB_STEP_SUMMARY
        npm audit --audit-level=low --format=json > audit-results.json || true
        
        # Parse and display results
        if [ -s audit-results.json ]; then
          VULNERABILITIES=$(cat audit-results.json | jq -r '.metadata.vulnerabilities | to_entries[] | "\(.key): \(.value)"' | tr '\n' ' ')
          if [ "$VULNERABILITIES" != " " ]; then
            echo "⚠️ **Security vulnerabilities found:**" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "$VULNERABILITIES" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Run \`npm audit fix\` to resolve automatically fixable issues." >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ **No security vulnerabilities found.**" >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "✅ **No security vulnerabilities found.**" >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Fail on high/critical vulnerabilities
      run: |
        # Fail the build if there are high or critical vulnerabilities
        npm audit --audit-level=high
    
    - name: Upload audit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-results
        path: audit-results.json
        retention-days: 30